name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ubuntu
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            mkdir -p ~/odoo-project
            cd ~/odoo-project
            # This creates the .env file on your EC2 using GitHub Secrets
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "EC2_IP=${{ secrets.EC2_HOST }}" >> .env
            
            # Pull the docker-compose file from your repo
            curl -O https://raw.githubusercontent.com/${{ github.repository }}/master/docker-compose.yaml
            
            sudo docker-compose pull
            sudo docker-compose up -d